joke/urls.py
from django.urls import path
from . import views

app_name = "joke"
urlpatterns = [
    path("", views.OverviewView.as_view(), name="overview"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("create", views.create, name="create"),
]

min_ex_tool/urls.py
from django.contrib import admin
from django.urls import path, include
from . import static_views


urlpatterns = [
    path("", static_views.render_page, {"p": "home.html", "context": {}}, name="home"),
    path("joke/", include("joke.urls")),
    path("admin/", admin.site.urls),
]

joke/models.py
from django.db import models

# Create your models here.
class Joke(models.Model):
    title = models.CharField(max_length=20)
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.title

joke/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
from .models import Joke
from .celery_tasks import capitalize


class OverviewView(generic.ListView):
    template_name = "overview.html"
    context_object_name = "joke_list"

    def get_queryset(self):
        return Joke.objects.order_by("title")


class DetailView(generic.DetailView):
    model = Joke
    template_name = "detail.html"


def create(request):

    if request.POST:
        title = request.POST["title"]
        future = capitalize.delay(title)
        title = future.get(timeout=5)
        joke = Joke.objects.create(title=title, text=request.POST["text"])
        joke.save()
        return HttpResponseRedirect(reverse("joke:detail", args=[joke.id]))
    context = dict()
    return render(request, "create.html", context)

joke/templates/create.html
<form action="{% url 'joke:create' %}" method="post">
{% csrf_token %}

<p>
<input type="text" name="title" id="title" value="">
</p>
<p>
<input type="text" name="text" id="text" value="">
</p>

<input type="submit" value="Save">

</form>

joke/templates/detail.html
<h1>
    {{ joke.title }}
</h1>
<p>
    {{ joke.text }}
</p>
<a href="{% url 'joke:overview' %}">back</a>

joke/templates/overview.html
{% if joke_list %}
    <ul>
    {% for joke in joke_list %}
        <li><a href="{% url 'joke:detail' joke.id %}">{{ joke.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No jokes are available.</p>
{% endif %}
<a href="{% url 'joke:create' %}">create new joke</a>
<p>
<a href="{% url 'home' %}">home</a>
</p>

templates/home.html
Home

<a href="{% url 'joke:overview' %}"><img src="static/a.png" alt="Water"></a>

<img src="static/b.png" alt="Cross">